cache_size_mb: 0

# Database configuration. This can also be a list of PG configs.
postgres:
  # Database connection string
  connection_string: ${DATABASE_URL}

  # # Maximum Postgres connections pool size [default: 20]
  # pool_size: 20

  # # Limit the number of table geo features included in a tile. Unlimited by default.
  # max_feature_count: 1000

  # # Control the automatic generation of bounds for spatial tables [default: quick]
  # # 'calc' - compute table geometry bounds on startup.
  # # 'quick' - same as 'calc', but the calculation will be aborted if it takes more than 5 seconds.
  # # 'skip' - do not compute table geometry bounds on startup.
  auto_bounds: skip

  # # Enable automatic discovery of tables and functions.
  # # You may set this to `false` to disable.
  auto_publish: false

  # Associative arrays of table sources
  tables:

    # --- Shared --- #

    # railway_line_high, see function below

    # --- Standard --- #

    standard_railway_text_stations_low:
      schema: public
      table: standard_railway_text_stations_low
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        station: string
        label: string
        name: string
        uic_ref: string

    standard_railway_text_stations_med:
      schema: public
      table: standard_railway_text_stations_med
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        station: string
        label: string
        name: string
        uic_ref: string

    standard_railway_turntables:
      schema: public
      table: turntables
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        id: integer
        osm_id: integer
        feature: string

    standard_railway_text_stations:
      schema: public
      table: standard_railway_text_stations
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        station: string
        label: string
        name: string
        count: integer
        uic_ref: string

    standard_railway_grouped_stations:
      schema: public
      table: standard_railway_grouped_stations
      srid: 3857
      geometry_column: way
      geometry_type: POLYGON
      properties:
        id: integer
        osm_id: integer
        railway: string
        station: string
        label: string
        name: string
        uic_ref: string

    standard_railway_symbols:
      schema: public
      table: standard_railway_symbols
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        feature: string

    railway_text_km:
      schema: public
      table: railway_text_km
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        pos: string
        pos_int: string
        zero: boolean

    standard_railway_switch_ref:
      schema: public
      table: standard_railway_switch_ref
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        ref: string
        # TODO: rename local_operated
        railway_local_operated: boolean

    # --- Speed --- #

    speed_railway_signals:
      schema: public
      table: speed_railway_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        feature0: string
        feature1: string
        type: string
        ref: string
        azimuth: number
        direction_both: boolean
        deactivated: boolean
        speed: integer

    # --- Signals --- #

    signals_railway_signals:
      schema: public
      table: signals_railway_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        railway: string
        ref: string
        ref_multiline: string
        feature0: string
        feature1: string
        feature2: string
        feature3: string
        feature4: string
        deactivated: boolean
        azimuth: number
        direction_both: boolean

    # signals_signal_boxes, see function below

    # --- Electrification --- #

    electrification_signals:
      schema: public
      table: electrification_signals
      srid: 3857
      geometry_column: way
      geometry_type: POINT
      properties:
        id: integer
        osm_id: integer
        feature: string
        azimuth: number
        direction_both: boolean
        ref: string
        deactivated: boolean
        frequency: number
        voltage: integer

  functions:

    # --- Shared --- #

    railway_line_high:
      schema: public
      function: railway_line_high
      maxzoom: 14

    # --- Signals --- #

    signals_signal_boxes:
      schema: public
      function: signals_signal_boxes
      minzoom: 8
      maxzoom: 14

fonts:
  - /config/fonts
