services:
  db:
    image: ghcr.io/hiddewie/openrailwaymap-import-db:latest
    build:
      context: db
    command: |
      postgres 
      -c shared_preload_libraries='pg_stat_statements'
    ports:
      - '5432:5432'
    shm_size: 1g
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - PGDATA=/var/lib/postgresql/postgres-data
    healthcheck:
      test: pg_isready -U postgres
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 5m

  import:
    image: ghcr.io/hiddewie/openrailwaymap-import:latest
    build:
      dockerfile: import/Dockerfile
      cache_from:
        - ghcr.io/hiddewie/openrailwaymap-import:latest
    command:
      - import
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data:/data
    environment:
      - PGHOST=db
      - PGUSER=postgres
      - PG_WORK_MEM
      - PG_MAINTENANCE_WORK_MEM
      - OSM2PGSQL_CACHE
      - OSM2PGSQL_NUMPROC
      - OSM2PGSQL_DATAFILE

  martin-cp:
    image: ghcr.io/maplibre/martin
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ['sh', '-c']
    command: |
      '
      export MARTIN="martin-cp --config /config/configuration.yml --mbtiles-type flat --on-duplicate override --skip-agg-tiles-hash --bbox=$$BBOX"
      [ "$$TILES" = "low-med" ] && $$MARTIN --min-zoom 0 --max-zoom 6 --source railway_line_low --output-file /tiles/railway_line_low.mbtiles && mbtiles summary /tiles/railway_line_low.mbtiles
      [ "$$TILES" = "low-med" ] && $$MARTIN --min-zoom 0 --max-zoom 6 --source standard_railway_text_stations_low --output-file /tiles/standard_railway_text_stations_low.mbtiles && mbtiles summary /tiles/standard_railway_text_stations_low.mbtiles
      [ "$$TILES" = "low-med" ] && $$MARTIN --min-zoom 7 --max-zoom 7 --source railway_line_med --output-file /tiles/railway_line_med.mbtiles && mbtiles summary /tiles/railway_line_med.mbtiles
      [ "$$TILES" = "low-med" ] && $$MARTIN --min-zoom 7 --max-zoom 7 --source standard_railway_text_stations_med --output-file /tiles/standard_railway_text_stations_med.mbtiles && mbtiles summary /tiles/standard_railway_text_stations_med.mbtiles
      [ "$$TILES" = "high" ] && $$MARTIN --min-zoom 8 --max-zoom "$$MAX_ZOOM" --source railway_line_high --output-file /tiles/railway_line_high.mbtiles && mbtiles summary /tiles/railway_line_high.mbtiles
      [ "$$TILES" = "standard" ] && $$MARTIN --min-zoom 8 --max-zoom "$$MAX_ZOOM" --source standard_railway_turntables,standard_railway_text_stations,standard_railway_symbols,standard_railway_text_km,standard_railway_switch_ref --output-file /tiles/standard.mbtiles && mbtiles summary /tiles/standard.mbtiles
      [ "$$TILES" = "speed" ] && $$MARTIN --min-zoom 8 --max-zoom "$$MAX_ZOOM" --source speed_railway_signals --output-file /tiles/speed.mbtiles && mbtiles summary /tiles/speed.mbtiles
      [ "$$TILES" = "signals" ] && $$MARTIN --min-zoom 8 --max-zoom "$$MAX_ZOOM" --source signals_railway_signals,signals_signal_boxes --output-file /tiles/signals.mbtiles && mbtiles summary /tiles/signals.mbtiles
      [ "$$TILES" = "electrification" ] && $$MARTIN --min-zoom 8 --max-zoom "$$MAX_ZOOM" --source electrification_signals --output-file /tiles/electrification.mbtiles && mbtiles summary /tiles/electrification.mbtiles
      true
      '

    volumes:
      - ./martin:/config
      - ./tiles:/tiles
    environment:
      # Europe center: -10.0,35.7,39.0,70.0
      # AT: 9.52678,46.36851,17.16273,48.90201
      # BE: 2.51357303225,49.5294835476,6.15665815596,51.4750237087
      # CH: 6.0974,45.8269,10.5579,47.7941
      # DE: 5.864417,47.26543,15.05078,55.14777
      # FI: 19.02427,59.28783,31.6159,70.09959
      # NL: 2.99,50.74753,7.230455,54.01786
      # PL-west: 15.0590,51.4957,19.5150,53.4155
      - BBOX
      - MIN_ZOOM=0
      - MAX_ZOOM=14
      - DATABASE_URL=postgresql://postgres@db:5432/gis
      - TILES

  martin:
    build:
      dockerfile: martin.Dockerfile
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./martin:/config
    environment:
      - DATABASE_URL=postgresql://postgres@db:5432/gis

  martin-static:
    build:
      dockerfile: martin-static.Dockerfile

  martin-proxy:
    build:
      dockerfile: proxy.Dockerfile
      args:
        PUBLIC_PROTOCOL: http
        PUBLIC_HOST: localhost:8000
    ports:
      - '8000:8000'
    environment:
      TILES_UPSTREAM: martin:3000
      API_UPSTREAM: api:5000
      PUBLIC_PROTOCOL: http
      PUBLIC_HOST: localhost:8000
      NGINX_RESOLVER: '127.0.0.11 ipv6=off'
      NGINX_CACHE_TTL: '0'
      CLIENT_CACHE_TTL_FRESH: '0'
      CLIENT_CACHE_TTL_STALE: '0'
    develop:
      watch:
        - action: rebuild
          path: proxy
        - action: rebuild
          path: features

  api:
    image: ghcr.io/hiddewie/openrailwaymap-api:latest
    build:
      context: api
      target: runtime
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    ports:
      - '5000:5000'

  api-import:
    image: ghcr.io/hiddewie/openrailwaymap-api:latest
    build:
      context: api
      target: import
