# TODO handle construction:*, proposed:*
signals_railway_line:
  train_protections:
    - { train_protection: 'etcs', legend: 'European Train Control System (ETCS)', color: 'blue' }
    - { train_protection: 'construction_etcs', legend: 'European Train Control System (under construction)', color: '#87CEFA' }
    - { train_protection: 'ctcs', legend: 'Chinese Train Control System (CTCS)', color: 'hsl(190, 100%, 40%)' }
    - { train_protection: 'zsi127', legend: 'ZSI 127', color: '#884400' }
    - { train_protection: 'ptc', legend: 'Positive train control (PTC)', color: '#cc0033' }
    - { train_protection: 'tvm', legend: 'Transmission Voie-Machine (TVM)', color: '#009966' }
    - { train_protection: 'kvb', legend: 'Contrôle de vitesse par balises (KVB)', color: '#66cc33' }
    - { train_protection: 'asfa', legend: 'Anuncio de Señales y Frenado Automático (ASFA)', color: '#ff9092' }
    - { train_protection: 'scmt', legend: 'Sistema Controllo Marcia Treno (SCMT)', color: '#dd11ff' }
    - { train_protection: 'atc', legend: 'Automatic train control (ATC)', color: '#6600cc' }
    - { train_protection: 'atb', legend: 'Automatische treinbeïnvloeding (ATB)', color: '#ff8c00' }
    - { train_protection: 'lzb', legend: 'Linienzugbeeinflussung (LZB)', color: 'red' }
    - { train_protection: 'pzb', legend: 'Punktförmige Zugbeeinflussung (PZB)', color: '#ffb900' }
    - { train_protection: 'acses', legend: 'Advanced Civil Speed Enforcement System (ACSES)', color: 'pink' }
    - { train_protection: 'als', legend: 'Автоматическая локомотивная сигнализация (ALS)', color: 'hsl(284, 100%, 40%)' }
    - { train_protection: 'atp', legend: 'Automatic Train Protection (ATP)', color: 'hsl(305, 100%, 40%)' }
    - { train_protection: 'aws', legend: 'Automatic Warning System (AWS)', color: 'hsl(50, 100%, 40%)' }
    - { train_protection: 'caws', legend: 'Continuous Automatic Warning System (CAWS)', color: 'hsl(60, 100%, 40%)' }
    - { train_protection: 'cbtc', legend: 'Communications Based Train Control (CBTC)', color: 'hsl(336, 100%, 40%)' }
    - { train_protection: 'ebicab', legend: 'EBICAB', color: 'pink' } # portugal & bulgaria
    - { train_protection: 'etms', legend: 'Electronic Train Management System (ETMS)', color: 'hsl(48, 100%, 40%)' }
    - { train_protection: 'evm', legend: 'Elektronikus Vonatmegállító (EVM)', color: 'hsl(137, 100%, 40%)' }
    - { train_protection: 'itcs', legend: 'Incremental Train Control System (ITCS)', color: 'hsl(35, 100%, 40%)' }
    - { train_protection: 'ls', legend: 'Liniový Systém (LS)', color: 'hsl(319, 100%, 40%)' }
    - { train_protection: 'octys', legend: 'Open Control of Trains, Interchangeable & Integrated System (OCTYS)', color: 'hsl(360, 100%, 40%)' }
    - { train_protection: 'ouragan', legend: 'Offre Urbaine Renouvelée et Améliorée, Gérée par un Automatisme Nouveau (OURAGAN)', color: 'hsl(48, 100%, 40%)' }
    - { train_protection: 'sacem', legend: 'Système d''Aide à la Conduite, à l''Exploitation et à la Maintenance (SACEM)', color: 'hsl(190, 100%, 40%)' }
    - { train_protection: 'saet', legend: 'Système d''Automatisation de l''Exploitation des Trains (SAET)', color: 'hsl(305, 100%, 40%)' }
    - { train_protection: 'shp', legend: 'Samoczynne Hamowanie Pociągu (SHP)', color: 'hsl(35, 100%, 40%)' }
    - { train_protection: 'ssc', legend: 'Sistema di Supporto alla Condotta (SSC)', color: 'hsl(155, 100%, 40%)' }
    - { train_protection: 'tasc', legend: '定位置停止装置 (TASC)', color: 'hsl(155, 100%, 40%)' }
    - { train_protection: 'tbl', legend: 'Transmissie Baken-Lokomotief (TBL)', color: 'hsl(305, 100%, 40%)' }
    - { train_protection: 'tpws', legend: 'Train Protection & Warning System (TPWS)', color: 'pink' }
    - { train_protection: 'zbs', legend: 'Zugbeeinflussung S-Bahn Berlin (ZBS)', color: 'hsl(155, 100%, 40%)' }
    - { train_protection: 'zsl90', legend: 'Zugsicherung mit Linienleiter 1990 (ZSL 90)', color: 'pink' }
    - { train_protection: 'zub', legend: 'Zugbeeinflussung (ZUB)', color: 'hsl(118, 100%, 30%)' }
    - { train_protection: 'satp', legend: 'Автоматическая блокировка (SATP)', color: 'hsl(187, 100%, 40%)' }
    - { train_protection: 'other', legend: '(other)', color: 'black' }

  features:
    - train_protection: ptc
      tags:
        - { tag: 'railway:ptc', value: 'yes' }

    - train_protection: etcs
      tags:
        - { tag: 'railway:etcs', value: 'yes' }

    - train_protection: etcs
      tags:
        - { tag: 'railway:etcs', value: '1' }

    - train_protection: etcs
      tags:
        - { tag: 'railway:etcs', value: '2' }

    - train_protection: etcs
      tags:
        - { tag: 'railway:etcs', value: '1;2' }

    - train_protection: etcs
      tags:
        - { tag: 'railway:etcs', value: '3' }

    - train_protection: construction_etcs
      tags:
        - { tag: 'construction:railway:etcs', value: 'yes' }

    - train_protection: construction_etcs
      tags:
        - { tag: 'construction:railway:etcs', value: '1' }

    - train_protection: construction_etcs
      tags:
        - { tag: 'construction:railway:etcs', value: '2' }

    - train_protection: construction_etcs
      tags:
        - { tag: 'construction:railway:etcs', value: '3' }

    - train_protection: asfa
      tags:
        - { tag: 'railway:asfa', value: 'yes' }

    - train_protection: asfa
      tags:
        - { tag: 'railway:asfa_fac', value: 'yes' }

    - train_protection: asfa
      tags:
        - { tag: 'railway:asfa_200', value: 'yes' }

    - train_protection: scmt
      tags:
        - { tag: 'railway:scmt', value: 'yes' }

    - train_protection: tvm
      tags:
        - { tag: 'railway:tvm', values: ['300', '430'] }

    - train_protection: kvb
      tags:
        - { tag: 'railway:kvb', value: 'yes' }

    - train_protection: atc
      tags:
        - { tag: 'railway:atc', value: 'yes' }

    - train_protection: atb
      tags:
        - { tag: 'railway:atb', value: 'yes' }

    - train_protection: atb
      tags:
        - { tag: 'railway:atb-eg', value: 'yes' }

    - train_protection: atb
      tags:
        - { tag: 'railway:atb-ng', value: 'yes' }

    - train_protection: atb
      tags:
        - { tag: 'railway:atb-vv', value: 'yes' }

    - train_protection: zsi127
      tags:
        - { tag: 'railway:zsi127', value: 'yes' }

    - train_protection: lzb
      tags:
        - { tag: 'railway:lzb', value: 'yes' }

    - train_protection: pzb
      tags:
        - { tag: 'railway:pzb', value: 'yes' }

    - train_protection: acses
      tags:
        - { tag: 'railway:acses', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:als', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:alsn', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:alst', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:also', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:als-en', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:alsr', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:als-ars', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:integra_signum:ALS', value: 'yes' }

    - train_protection: als
      tags:
        - { tag: 'railway:integra_signum:ALSO', value: 'yes' }

    - train_protection: atp
      tags:
        - { tag: 'railway:atp', value: 'yes' }

    - train_protection: aws
      tags:
        - { tag: 'railway:aws', value: 'yes' }

    - train_protection: caws
      tags:
        - { tag: 'railway:caws', value: 'yes' }

    - train_protection: cbtc
      tags:
        - { tag: 'railway:cbtc', values: ['yes', 'uto', 'sto', 'dto'] }

    - train_protection: ctcs
      tags:
        - { tag: 'railway:ctcs', values: ['yes', '0', '1', '2', '3D', '4'] }

    - train_protection: ebicab
      tags:
        - { tag: 'railway:ebicab', values: ['yes', '700', '900'] }

    - train_protection: etms
      tags:
        - { tag: 'railway:etms', value: 'yes' }

    - train_protection: evm
      tags:
        - { tag: 'railway:evm', value: 'yes' }

    - train_protection: itcs
      tags:
        - { tag: 'railway:itcs', value: 'yes' }

    - train_protection: ls
      tags:
        - { tag: 'railway:ls', value: 'yes' }

    - train_protection: octys
      tags:
        - { tag: 'railway:octys', value: 'yes' }

    - train_protection: ouragan
      tags:
        - { tag: 'railway:ouragan', value: 'yes' }

    - train_protection: sacem
      tags:
        - { tag: 'railway:sacem', value: 'yes' }

    - train_protection: saet
      tags:
        - { tag: 'railway:saet', value: 'yes' }

    - train_protection: shp
      tags:
        - { tag: 'railway:shp', value: 'yes' }

    - train_protection: ssc
      tags:
        - { tag: 'railway:ssc', value: 'yes' }

    - train_protection: tasc
      tags:
        - { tag: 'railway:tasc', value: 'yes' }

    - train_protection: tbl
      tags:
        - { tag: 'railway:tbl', values: ['yes', '1', '1+', '2'] }

    - train_protection: tpws
      tags:
        - { tag: 'railway:tpws', value: 'yes' }

    - train_protection: zbs
      tags:
        - { tag: 'railway:zbs', value: 'yes' }

    - train_protection: zsl90
      tags:
        - { tag: 'railway:zsl90', value: 'yes' }

    - train_protection: zub
      tags:
        - { tag: 'railway:zub', value: 'yes' }

    - train_protection: zub
      tags:
        - { tag: 'railway:zub121', value: 'yes' }

    - train_protection: zub
      tags:
        - { tag: 'railway:zub122', value: 'yes' }

    - train_protection: zub
      tags:
        - { tag: 'railway:zub123', value: 'yes' }

    - train_protection: zub
      tags:
        - { tag: 'railway:zub222c', value: 'yes' }

    - train_protection: satp
      tags:
        - { tag: 'railway:satp', value: 'yes' }

    - train_protection: satp
      tags:
        - { tag: 'railway:atp3b', value: 'yes' }

    - train_protection: satp
      tags:
        - { tag: 'railway:atp4b', value: 'yes' }

    - train_protection: other
      tags:
        - { tag: 'railway:pzb', value: 'no' }
        - { tag: 'railway:lzb', value: 'no' }
        - { tag: 'railway:etcs', value: 'no' }

    - train_protection: other
      tags:
        - { tag: 'railway:atb', value: 'no' }
        - { tag: 'railway:etcs', value: 'no' }

    - train_protection: other
      tags:
        - { tag: 'railway:atc', value: 'no' }
        - { tag: 'railway:etcs', value: 'no' }

    - train_protection: other
      tags:
        - { tag: 'railway:scmt', value: 'no' }
        - { tag: 'railway:etcs', value: 'no' }

    - train_protection: other
      tags:
        - { tag: 'railway:asfa', value: 'no' }
        - { tag: 'railway:etcs', value: 'no' }

    - train_protection: other
      tags:
        - { tag: 'railway:kvb', value: 'no' }
        - { tag: 'railway:tvm', value: 'no' }
        - { tag: 'railway:etcs', value: 'no' }

    - train_protection: other
      tags:
        - { tag: 'railway:ls', value: 'no' }
        - { tag: 'railway:etcs', value: 'no' }

    - train_protection: other
      tags:
        - { tag: 'railway:zsi127', value: 'no' }
