name: Deploy

on:
  workflow_dispatch: ~

jobs:
  deploy-proxy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    environment: proxy-production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Setup Fly
      #  uses: superfly/flyctl-actions/setup-flyctl@master

      # Manually write import bounds, to decouple proxy from tile generation/import
      - name: Output import bounds
        run: |
          echo '[[-135.2,42.1], [-53.0, 60.8]]' > data/import/bounds.json

      #- name: Deploy
      #  env:
      #    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #  run: |
      #    flyctl deploy --config proxy.fly.toml --local-only

  generate-tiles:
    name: Generate tiles
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Generate with (Fish shell):
        #   for i in (seq -10 38); echo "- '$i,35,"(math $i + 1)",70'"; end
        bbox:
          - '-167,14,-166,72'
          - '-166,14,-165,72'
          - '-165,14,-164,72'
          - '-164,14,-163,72'
          - '-163,14,-162,72'
          - '-162,14,-161,72'
          - '-161,14,-160,72'
          - '-160,14,-159,72'
          - '-159,14,-158,72'
          - '-158,14,-157,72'
          - '-157,14,-156,72'
          - '-156,14,-155,72'
          - '-155,14,-154,72'
          - '-154,14,-153,72'
          - '-153,14,-152,72'
          - '-152,14,-151,72'
          - '-151,14,-150,72'
          - '-150,14,-149,72'
          - '-149,14,-148,72'
          - '-148,14,-147,72'
          - '-147,14,-146,72'
          - '-146,14,-145,72'
          - '-145,14,-144,72'
          - '-144,14,-143,72'
          - '-143,14,-142,72'
          - '-142,14,-141,72'
          - '-141,14,-140,72'
          - '-140,14,-139,72'
          - '-139,14,-138,72'
          - '-138,14,-137,72'
          - '-137,14,-136,72'
          - '-136,14,-135,72'
          - '-135,14,-134,72'
          - '-134,14,-133,72'
          - '-133,14,-132,72'
          - '-132,14,-131,72'
          - '-131,14,-130,72'
          - '-130,14,-129,72'
          - '-129,14,-128,72'
          - '-128,14,-127,72'
          - '-127,14,-126,72'
          - '-126,14,-125,72'
          - '-125,14,-124,72'
          - '-124,14,-123,72'
          - '-123,14,-122,72'
          - '-122,14,-121,72'
          - '-121,14,-120,72'
          - '-120,14,-119,72'
          - '-119,14,-118,72'
          - '-118,14,-117,72'
          - '-117,14,-116,72'
          - '-116,14,-115,72'
          - '-115,14,-114,72'
          - '-114,14,-113,72'
          - '-113,14,-112,72'
          - '-112,14,-111,72'
          - '-111,14,-110,72'
          - '-110,14,-109,72'
          - '-109,14,-108,72'
          - '-108,14,-107,72'
          - '-107,14,-106,72'
          - '-106,14,-105,72'
          - '-105,14,-104,72'
          - '-104,14,-103,72'
          - '-103,14,-102,72'
          - '-102,14,-101,72'
          - '-101,14,-100,72'
          - '-100,14,-99,72'
          - '-99,14,-98,72'
          - '-98,14,-97,72'
          - '-97,14,-96,72'
          - '-96,14,-95,72'
          - '-95,14,-94,72'
          - '-94,14,-93,72'
          - '-93,14,-92,72'
          - '-92,14,-91,72'
          - '-91,14,-90,72'
          - '-90,14,-89,72'
          - '-89,14,-88,72'
          - '-88,14,-87,72'
          - '-87,14,-86,72'
          - '-86,14,-85,72'
          - '-85,14,-84,72'
          - '-84,14,-83,72'
          - '-83,14,-82,72'
          - '-82,14,-81,72'
          - '-81,14,-80,72'
          - '-80,14,-79,72'
          - '-79,14,-78,72'
          - '-78,14,-77,72'
          - '-77,14,-76,72'
          - '-76,14,-75,72'
          - '-75,14,-74,72'
          - '-74,14,-73,72'
          - '-73,14,-72,72'
          - '-72,14,-71,72'
          - '-71,14,-70,72'
          - '-70,14,-69,72'
          - '-69,14,-68,72'
          - '-68,14,-67,72'
          - '-67,14,-66,72'
          - '-66,14,-65,72'
          - '-65,14,-64,72'
          - '-64,14,-63,72'
          - '-63,14,-62,72'
          - '-62,14,-61,72'
          - '-61,14,-60,72'
          - '-60,14,-59,72'
          - '-59,14,-58,72'
          - '-58,14,-57,72'
          - '-57,14,-56,72'
          - '-56,14,-55,72'
          - '-55,14,-54,72'
          - '-54,14,-53,72'
          - '-53,14,-52,72'
          - '-52,14,-51,72'
          - '-51,14,-50,72'
          - '-50,14,-49,72'
          - '-49,14,-48,72'
          - '-48,14,-47,72'
          - '-47,14,-46,72'
          - '-46,14,-45,72'
          - '-45,14,-44,72'
          - '-44,14,-43,72'
          - '-43,14,-42,72'
          - '-42,14,-41,72'
          - '-41,14,-40,72'
          - '-40,14,-39,72'
          - '-39,14,-38,72'
          - '-38,14,-37,72'
          - '-37,14,-36,72'
          - '-36,14,-35,72'
          - '-35,14,-34,72'
          - '-34,14,-33,72'
          - '-33,14,-32,72'
          - '-32,14,-31,72'
          - '-31,14,-30,72'
          - '-30,14,-29,72'
          - '-29,14,-28,72'
          - '-28,14,-27,72'
          - '-27,14,-26,72'
          - '-26,14,-25,72'
          - '-25,14,-24,72'
          - '-24,14,-23,72'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull database
        run: |
          docker compose pull db
          docker compose up --no-build --pull never --wait db

      - name: Generate tiles
        env:
          BBOX: ${{ matrix.bbox }}
        run: |
          docker compose run --no-deps martin-cp

          mkdir -p "tiles/split/${{ matrix.bbox }}"
          mv tiles/*.mbtiles "tiles/split/${{ matrix.bbox }}"

      - name: List generated tiles
        run: |
          ls -lah tiles/split/${{ matrix.bbox }}/*.mbtiles

      - uses: actions/upload-artifact@v4
        with:
          name: tiles-${{ matrix.bbox }}
          path: |
            tiles/split
          if-no-files-found: error
          retention-days: 3

  deploy-tiles:
    name: Merge and deploy tiles
    runs-on: ubuntu-latest
    needs: generate-tiles
    environment: tiles-production

    env:
      # Generate with (Fish shell):
      #   for i in (seq -10 38); echo -n "$i,35,"(math $i + 1)",70 "; end
      BBOXES: '-167,14,-166,72 -166,14,-165,72 -165,14,-164,72 -164,14,-163,72 -163,14,-162,72 -162,14,-161,72 -161,14,-160,72 -160,14,-159,72 -159,14,-158,72 -158,14,-157,72 -157,14,-156,72 -156,14,-155,72 -155,14,-154,72 -154,14,-153,72 -153,14,-152,72 -152,14,-151,72 -151,14,-150,72 -150,14,-149,72 -149,14,-148,72 -148,14,-147,72 -147,14,-146,72 -146,14,-145,72 -145,14,-144,72 -144,14,-143,72 -143,14,-142,72 -142,14,-141,72 -141,14,-140,72 -140,14,-139,72 -139,14,-138,72 -138,14,-137,72 -137,14,-136,72 -136,14,-135,72 -135,14,-134,72 -134,14,-133,72 -133,14,-132,72 -132,14,-131,72 -131,14,-130,72 -130,14,-129,72 -129,14,-128,72 -128,14,-127,72 -127,14,-126,72 -126,14,-125,72 -125,14,-124,72 -124,14,-123,72 -123,14,-122,72 -122,14,-121,72 -121,14,-120,72 -120,14,-119,72 -119,14,-118,72 -118,14,-117,72 -117,14,-116,72 -116,14,-115,72 -115,14,-114,72 -114,14,-113,72 -113,14,-112,72 -112,14,-111,72 -111,14,-110,72 -110,14,-109,72 -109,14,-108,72 -108,14,-107,72 -107,14,-106,72 -106,14,-105,72 -105,14,-104,72 -104,14,-103,72 -103,14,-102,72 -102,14,-101,72 -101,14,-100,72 -100,14,-99,72 -99,14,-98,72 -98,14,-97,72 -97,14,-96,72 -96,14,-95,72 -95,14,-94,72 -94,14,-93,72 -93,14,-92,72 -92,14,-91,72 -91,14,-90,72 -90,14,-89,72 -89,14,-88,72 -88,14,-87,72 -87,14,-86,72 -86,14,-85,72 -85,14,-84,72 -84,14,-83,72 -83,14,-82,72 -82,14,-81,72 -81,14,-80,72 -80,14,-79,72 -79,14,-78,72 -78,14,-77,72 -77,14,-76,72 -76,14,-75,72 -75,14,-74,72 -74,14,-73,72 -73,14,-72,72 -72,14,-71,72 -71,14,-70,72 -70,14,-69,72 -69,14,-68,72 -68,14,-67,72 -67,14,-66,72 -66,14,-65,72 -65,14,-64,72 -64,14,-63,72 -63,14,-62,72 -62,14,-61,72 -61,14,-60,72 -60,14,-59,72 -59,14,-58,72 -58,14,-57,72 -57,14,-56,72 -56,14,-55,72 -55,14,-54,72 -54,14,-53,72 -53,14,-52,72 -52,14,-51,72 -51,14,-50,72 -50,14,-49,72 -49,14,-48,72 -48,14,-47,72 -47,14,-46,72 -46,14,-45,72 -45,14,-44,72 -44,14,-43,72 -43,14,-42,72 -42,14,-41,72 -41,14,-40,72 -40,14,-39,72 -39,14,-38,72 -38,14,-37,72 -37,14,-36,72 -36,14,-35,72 -35,14,-34,72 -34,14,-33,72 -33,14,-32,72 -32,14,-31,72 -31,14,-30,72 -30,14,-29,72 -29,14,-28,72 -28,14,-27,72 -27,14,-26,72 -26,14,-25,72 -25,14,-24,72 -24,14,-23,72'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Setup Fly
      #  uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          pattern: tiles-*
          merge-multiple: true
          path: tiles/split

      - name: Merge tiles
        run: |
          docker compose run --entrypoint /tiles/merge.sh -e BBOXES --no-deps martin-cp

      - name: Delete split tiles
        run: |
          for bbox in $BBOXES; do
            rm -rf "tiles/split/$bbox"
          done

      - name: List generated tiles
        run: |
          ls -lah tiles/*.mbtiles

      #- name: Deploy
      #  env:
      #    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #  run: |
      #    flyctl deploy --config martin-static.fly.toml --local-only

  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    environment: api-production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #- name: Setup Fly
      #  uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Pull database
        run: |
          docker compose pull db
          docker compose up --no-build --pull never --wait db

      - name: Prepare and build API container
        env:
          SKIP_CLEANUP: 'yes'
        run: |
          api/prepare-api.sh

      - name: Print import logs
        if: ${{ always() }}
        run: |
          docker compose logs api-import

      #- name: Deploy
      #  env:
      #    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      #  run: |
      #    flyctl deploy --config api.fly.toml --local-only api
